// Synthetic, educational FSP training cases. Not real patient data.
// caseData and rubric are server-only — never sent to the client as-is
// (see lib/ai/patient.ts, which extracts only what a given turn needs).

export interface CaseSeed {
  slug: string;
  title: string;
  specialty: string;
  difficulty: 1 | 2 | 3;
  estimatedMinutes: number;
  patientName: string;
  patientAge: number;
  patientSex: 'männlich' | 'weiblich';
  openingStatement: string;
  caseData: {
    chiefComplaint: string;
    onset: string;
    duration: string;
    characteristics: string[];
    positiveFindings: string[];
    negativeFindings: string[];
    pastMedicalHistory: string[];
    medications: string[];
    allergies: string[];
    familyHistory: string[];
    socialHistory: string;
    smoking: string;
    alcohol: string;
    occupation: string;
    patientConcerns: string;
    emotionalState: string;
    likelyDiagnosis: string;
  };
  rubric: {
    requiredQuestions: string[];
    optionalQuestions: string[];
    criticalOmissions: string[];
    patientLanguageTargets: string[];
    terminologyTargets: string[];
    communicationTargets: string[];
    scoringWeights: {
      anamnesis: number;
      communication: number;
      patientLanguage: number;
      medicalTerminology: number;
      completeness: number;
      languageAccuracy: number;
    };
  };
}

export const CASE_SEEDS: CaseSeed[] = [
  {
    slug: 'thoraxschmerzen-01',
    title: 'Akute Thoraxschmerzen',
    specialty: 'Kardiologie',
    difficulty: 2,
    estimatedMinutes: 15,
    patientName: 'Herr Bauer',
    patientAge: 58,
    patientSex: 'männlich',
    openingStatement: 'Guten Tag Doktor, ich habe seit heute Morgen ein Engegefühl in der Brust.',
    caseData: {
      chiefComplaint: 'Retrosternales Engegefühl, belastungsabhängig',
      onset: 'Heute Morgen beim Treppensteigen',
      duration: '3 Stunden, episodisch, je ca. 10 Minuten',
      characteristics: ['drückend, nicht stechend', 'Ausstrahlung in den linken Arm', 'verstärkt bei Anstrengung, bessert in Ruhe'],
      positiveFindings: ['Schwitzen während der Episoden', 'leichte Luftnot', 'Übelkeit einmalig'],
      negativeFindings: ['kein Fieber', 'kein Husten', 'kein atemabhängiger Schmerz', 'keine Beinschwellung'],
      pastMedicalHistory: ['arterielle Hypertonie seit 10 Jahren', 'Typ-2-Diabetes seit 5 Jahren'],
      medications: ['Ramipril 5mg', 'Metformin 1000mg'],
      allergies: ['keine bekannt'],
      familyHistory: ['Vater: Herzinfarkt mit 60 Jahren'],
      socialHistory: 'verheiratet, zwei erwachsene Kinder, arbeitet als Bürokaufmann',
      smoking: '20 py, aktuell weiterhin rauchend',
      alcohol: 'gelegentlich, ca. 2 Einheiten/Woche',
      occupation: 'Bürokaufmann, sitzende Tätigkeit',
      patientConcerns: 'Angst vor einem Herzinfarkt, da der Vater daran verstarb',
      emotionalState: 'ängstlich, angespannt',
      likelyDiagnosis: 'Instabile Angina pectoris bei bekannten kardiovaskulären Risikofaktoren',
    },
    rubric: {
      requiredQuestions: [
        'Charakter des Schmerzes (drückend/stechend)',
        'Ausstrahlung',
        'Belastungsabhängigkeit',
        'Begleitsymptome (Schwitzen, Luftnot, Übelkeit)',
        'Dauer der Episoden',
        'Kardiovaskuläre Risikofaktoren (Rauchen, Diabetes, Hypertonie)',
        'Familienanamnese bezüglich Herzerkrankungen',
        'Aktuelle Medikation',
      ],
      optionalQuestions: ['Voroperationen', 'frühere ähnliche Episoden', 'Alkoholkonsum'],
      criticalOmissions: [
        'Nichterfragen der Ausstrahlung',
        'Nichterfragen von Risikofaktoren (Rauchen, Diabetes)',
        'Kein Hinweis auf die Dringlichkeit/notfallmäßige Abklärung gegenüber dem Patienten',
      ],
      patientLanguageTargets: ['Engegefühl statt "Angina pectoris" im Patientengespräch verwenden'],
      terminologyTargets: ['Angina pectoris', 'Belastungsdyspnoe', 'kardiovaskuläre Risikofaktoren'],
      communicationTargets: ['Ängste des Patienten ernst nehmen', 'ruhige, klare Kommunikation bei Verdacht auf Notfall'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'dyspnoe-01',
    title: 'Zunehmende Atemnot',
    specialty: 'Pneumologie',
    difficulty: 2,
    estimatedMinutes: 15,
    patientName: 'Frau Schmidt',
    patientAge: 67,
    patientSex: 'weiblich',
    openingStatement: 'Ich bekomme seit ein paar Tagen immer schlechter Luft, besonders wenn ich mich hinlege.',
    caseData: {
      chiefComplaint: 'Progrediente Dyspnoe, Orthopnoe',
      onset: 'Schleichend über 5 Tage',
      duration: '5 Tage, zunehmend',
      characteristics: ['Orthopnoe (3 Kissen)', 'Belastungsdyspnoe bei geringer Anstrengung'],
      positiveFindings: ['beidseitige Knöchelödeme', 'Gewichtszunahme 3kg in einer Woche', 'nächtlicher Husten'],
      negativeFindings: ['kein Fieber', 'kein Thoraxschmerz', 'kein Hämoptyse'],
      pastMedicalHistory: ['chronische Herzinsuffizienz NYHA II', 'Vorhofflimmern'],
      medications: ['Bisoprolol', 'Furosemid', 'Apixaban'],
      allergies: ['keine bekannt'],
      familyHistory: ['unauffällig'],
      socialHistory: 'lebt allein, Rentnerin, Tochter wohnt in der Nähe',
      smoking: 'nie geraucht',
      alcohol: 'kein Alkoholkonsum',
      occupation: 'Rentnerin, ehemals Lehrerin',
      patientConcerns: 'Sorge, ins Krankenhaus zu müssen und die Unabhängigkeit zu verlieren',
      emotionalState: 'besorgt, etwas erschöpft',
      likelyDiagnosis: 'Dekompensierte chronische Herzinsuffizienz',
    },
    rubric: {
      requiredQuestions: [
        'Orthopnoe (Anzahl Kissen)',
        'Beinödeme',
        'Gewichtsveränderung',
        'Bekannte Herzinsuffizienz/Vorerkrankungen',
        'Aktuelle Medikation und Compliance',
        'Verlauf über die letzten Tage',
      ],
      optionalQuestions: ['Nykturie', 'Appetit', 'Nachtschweiß'],
      criticalOmissions: ['Nichterfragen von Orthopnoe', 'Nichterfragen der Medikamenten-Compliance (Diuretikum)'],
      patientLanguageTargets: ['"Wasser in den Beinen" statt "periphere Ödeme" verwenden'],
      terminologyTargets: ['Orthopnoe', 'Herzinsuffizienz', 'Diuretikum', 'Dekompensation'],
      communicationTargets: ['Sorgen um Selbstständigkeit ansprechen', 'verständlich erklären warum Gewicht wichtig ist'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'bauchschmerzen-01',
    title: 'Akute Unterbauchschmerzen',
    specialty: 'Gastroenterologie',
    difficulty: 1,
    estimatedMinutes: 15,
    patientName: 'Herr Yilmaz',
    patientAge: 24,
    patientSex: 'männlich',
    openingStatement: 'Ich habe seit heute Nacht starke Schmerzen im Bauch, die immer schlimmer werden.',
    caseData: {
      chiefComplaint: 'Rechtsseitiger Unterbauchschmerz',
      onset: 'Begann periumbilikal vor 12 Stunden, wanderte in den rechten Unterbauch',
      duration: '12 Stunden, zunehmend',
      characteristics: ['erst dumpf periumbilikal, jetzt scharf rechts unten', 'verstärkt bei Bewegung'],
      positiveFindings: ['Übelkeit', 'einmaliges Erbrechen', 'subfebrile Temperatur (37,8°C)', 'Appetitlosigkeit'],
      negativeFindings: ['kein Durchfall', 'kein Blut im Stuhl', 'keine Miktionsbeschwerden'],
      pastMedicalHistory: ['keine relevanten Vorerkrankungen'],
      medications: ['keine'],
      allergies: ['keine bekannt'],
      familyHistory: ['unauffällig'],
      socialHistory: 'Student, lebt in einer WG',
      smoking: 'Nichtraucher',
      alcohol: 'gelegentlich am Wochenende',
      occupation: 'Student (Informatik)',
      patientConcerns: 'Angst vor einer Operation',
      emotionalState: 'ängstlich, Schmerzen deutlich sichtbar',
      likelyDiagnosis: 'Akute Appendizitis',
    },
    rubric: {
      requiredQuestions: [
        'Schmerzwanderung (periumbilikal zu rechtem Unterbauch)',
        'Charakter und Intensität des Schmerzes',
        'Begleitsymptome (Übelkeit, Erbrechen, Fieber)',
        'Appetit',
        'Stuhlgang und Miktion',
        'Zeitlicher Verlauf',
      ],
      optionalQuestions: ['ähnliche frühere Episoden', 'Ernährung vor Symptombeginn'],
      criticalOmissions: ['Nichterfragen der Schmerzwanderung', 'Nichterfragen von Fieber'],
      patientLanguageTargets: ['"Blinddarmentzündung" statt "Appendizitis" im Patientengespräch verwenden'],
      terminologyTargets: ['Appendizitis', 'Peritonismus', 'periumbilikal'],
      communicationTargets: ['OP-Ängste ernst nehmen und einfühlsam ansprechen'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'kopfschmerzen-01',
    title: 'Wiederkehrende Kopfschmerzen',
    specialty: 'Neurologie',
    difficulty: 1,
    estimatedMinutes: 15,
    patientName: 'Frau Weber',
    patientAge: 32,
    patientSex: 'weiblich',
    openingStatement: 'Ich habe seit Jahren immer wieder starke Kopfschmerzen, aktuell wieder seit gestern.',
    caseData: {
      chiefComplaint: 'Rezidivierende, einseitige, pulsierende Kopfschmerzen',
      onset: 'Erstmals vor 10 Jahren, aktuelle Episode seit gestern Nachmittag',
      duration: 'Episoden dauern meist 1-2 Tage, aktuell seit 18 Stunden',
      characteristics: ['einseitig, wechselnd', 'pulsierend', 'verstärkt bei Bewegung'],
      positiveFindings: ['Übelkeit', 'Licht- und Geräuschempfindlichkeit', 'gelegentlich Sehstörungen vor Beginn (Aura)'],
      negativeFindings: ['kein Fieber', 'kein Nackensteife', 'keine neurologischen Ausfälle', 'kein Trauma'],
      pastMedicalHistory: ['Migräne, Erstdiagnose vor 10 Jahren'],
      medications: ['Ibuprofen bei Bedarf'],
      allergies: ['keine bekannt'],
      familyHistory: ['Mutter hat ebenfalls Migräne'],
      socialHistory: 'verheiratet, arbeitet als Grafikdesignerin, viel Bildschirmarbeit',
      smoking: 'Nichtraucherin',
      alcohol: 'selten',
      occupation: 'Grafikdesignerin',
      patientConcerns: 'Beeinträchtigung der Arbeitsfähigkeit durch häufige Attacken',
      emotionalState: 'frustriert, aber gefasst',
      likelyDiagnosis: 'Migräne mit Aura',
    },
    rubric: {
      requiredQuestions: [
        'Charakter (pulsierend/drückend)',
        'Lokalisation (einseitig/beidseitig)',
        'Begleitsymptome (Übelkeit, Photophobie, Phonophobie)',
        'Aura-Symptome',
        'Häufigkeit und Dauer der Episoden',
        'Familienanamnese',
        'Auslöser (Trigger)',
      ],
      optionalQuestions: ['Menstruationszyklus als Trigger', 'Schlafqualität'],
      criticalOmissions: ['Nichterfragen von Warnzeichen (Fieber, Nackensteife, neurologische Ausfälle)'],
      patientLanguageTargets: ['"pochender Kopfschmerz" statt "pulsierende Cephalgie" im Gespräch verwenden'],
      terminologyTargets: ['Migräne', 'Aura', 'Photophobie', 'Phonophobie'],
      communicationTargets: ['Auswirkung auf Alltag/Beruf erfragen und ernst nehmen'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'schwindel-01',
    title: 'Akuter Schwindel',
    specialty: 'Neurologie',
    difficulty: 2,
    estimatedMinutes: 15,
    patientName: 'Herr Krause',
    patientAge: 71,
    patientSex: 'männlich',
    openingStatement: 'Mir ist seit heute Morgen sehr schwindelig, alles dreht sich.',
    caseData: {
      chiefComplaint: 'Akuter Drehschwindel',
      onset: 'Heute Morgen beim Aufstehen, plötzlich',
      duration: 'Anhaltend seit 4 Stunden',
      characteristics: ['Drehschwindel', 'verstärkt bei Kopfbewegung', 'Besserung im Liegen mit geschlossenen Augen'],
      positiveFindings: ['Übelkeit', 'einmaliges Erbrechen', 'Gangunsicherheit'],
      negativeFindings: ['keine Doppelbilder', 'keine Sprach- oder Schluckstörung', 'keine Lähmungserscheinungen', 'kein Hörverlust'],
      pastMedicalHistory: ['arterielle Hypertonie', 'Vorhofflimmern unter Antikoagulation'],
      medications: ['Apixaban', 'Amlodipin'],
      allergies: ['keine bekannt'],
      familyHistory: ['unauffällig'],
      socialHistory: 'verwitwet, lebt allein',
      smoking: 'Ex-Raucher, vor 15 Jahren aufgehört',
      alcohol: 'gelegentlich',
      occupation: 'Rentner, ehemals Ingenieur',
      patientConcerns: 'Angst vor einem Schlaganfall, da er unter Blutverdünnung steht',
      emotionalState: 'ängstlich, unsicher',
      likelyDiagnosis: 'Differenzialdiagnose peripherer (BPLS) vs. zentraler Schwindel — abklärungsbedürftig bei vaskulären Risikofaktoren',
    },
    rubric: {
      requiredQuestions: [
        'Charakter (Dreh- vs. Schwankschwindel)',
        'Auslöser/Verstärkung durch Kopfbewegung',
        'Begleitsymptome (Doppelbilder, Sprach-/Schluckstörung, Lähmung, Hörverlust)',
        'Dauer und Verlauf',
        'Kardiovaskuläre Risikofaktoren und Antikoagulation',
        'Sturzrisiko/Gangunsicherheit',
      ],
      optionalQuestions: ['frühere ähnliche Episoden', 'Ohrgeräusche (Tinnitus)'],
      criticalOmissions: [
        'Nichterfragen zentraler Warnzeichen (Doppelbilder, Sprachstörung, Lähmung) — kritisch zur Abgrenzung Schlaganfall',
        'Nichterfragen der Antikoagulation',
      ],
      patientLanguageTargets: ['"Drehschwindel, als würde sich alles drehen" als patientenverständliche Beschreibung verwenden'],
      terminologyTargets: ['Vertigo', 'Nystagmus', 'zentraler vs. peripherer Schwindel'],
      communicationTargets: ['Angst vor Schlaganfall ansprechen, ohne unnötig zu beunruhigen'],
      scoringWeights: { anamnesis: 35, communication: 15, patientLanguage: 10, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'ruckenschmerzen-01',
    title: 'Akute Rückenschmerzen',
    specialty: 'Orthopädie',
    difficulty: 1,
    estimatedMinutes: 12,
    patientName: 'Frau Novak',
    patientAge: 45,
    patientSex: 'weiblich',
    openingStatement: 'Ich habe seit zwei Tagen starke Schmerzen im unteren Rücken, die ins Bein ziehen.',
    caseData: {
      chiefComplaint: 'Akute Lumbalgie mit Ausstrahlung ins linke Bein',
      onset: 'Vor zwei Tagen beim Heben einer schweren Kiste',
      duration: '2 Tage',
      characteristics: ['ziehender Schmerz von der Lendenwirbelsäule ins linke Bein', 'verstärkt beim Sitzen und Husten'],
      positiveFindings: ['Kribbeln im linken Unterschenkel'],
      negativeFindings: ['keine Lähmung', 'keine Blasen- oder Mastdarmstörung', 'kein Reithosen-Taubheitsgefühl', 'kein Fieber'],
      pastMedicalHistory: ['gelegentliche Rückenschmerzen in der Vergangenheit'],
      medications: ['keine regelmäßige Medikation'],
      allergies: ['keine bekannt'],
      familyHistory: ['nicht relevant'],
      socialHistory: 'verheiratet, arbeitet im Lager, körperlich anstrengende Tätigkeit',
      smoking: 'Nichtraucherin',
      alcohol: 'selten',
      occupation: 'Lagermitarbeiterin',
      patientConcerns: 'Sorge um Arbeitsfähigkeit, da körperliche Arbeit',
      emotionalState: 'besorgt wegen Job, aber kooperativ',
      likelyDiagnosis: 'Lumboischialgie bei Verdacht auf Bandscheibenvorfall',
    },
    rubric: {
      requiredQuestions: [
        'Auslösendes Ereignis (Heben, Trauma)',
        'Ausstrahlung und genaue Lokalisation',
        'Sensibilitätsstörungen (Kribbeln, Taubheit)',
        'Red-Flag-Symptome (Blasen-/Mastdarmstörung, Reithosenanästhesie, Lähmung)',
        'Verstärkung durch Husten/Pressen',
        'Berufliche Belastung',
      ],
      optionalQuestions: ['frühere Rückenprobleme', 'Schmerzintensität auf einer Skala'],
      criticalOmissions: ['Nichterfragen von Red-Flag-Symptomen (Kauda-Syndrom-Zeichen)'],
      patientLanguageTargets: ['"Ausstrahlung ins Bein" statt "radikuläre Schmerzausstrahlung" verwenden'],
      terminologyTargets: ['Lumboischialgie', 'Bandscheibenvorfall', 'Kauda-Syndrom'],
      communicationTargets: ['Arbeitsplatzsorgen ernst nehmen, realistische Erwartungen zur Genesungsdauer vermitteln'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'fieber-01',
    title: 'Unklares Fieber',
    specialty: 'Infektiologie',
    difficulty: 2,
    estimatedMinutes: 15,
    patientName: 'Herr Ali',
    patientAge: 29,
    patientSex: 'männlich',
    openingStatement: 'Ich habe seit drei Tagen hohes Fieber, das einfach nicht runtergeht.',
    caseData: {
      chiefComplaint: 'Fieber unklarer Ursache seit drei Tagen',
      onset: 'Vor drei Tagen, plötzlich',
      duration: '3 Tage, bis 39,5°C',
      characteristics: ['undulierend, abends höher', 'begleitet von Schüttelfrost'],
      positiveFindings: ['Kopfschmerzen', 'Gliederschmerzen', 'Abgeschlagenheit', 'leichter Husten'],
      negativeFindings: ['kein Ausschlag', 'keine Nackensteife', 'kein Durchfall', 'keine Dysurie'],
      pastMedicalHistory: ['keine relevanten Vorerkrankungen'],
      medications: ['Paracetamol bei Bedarf'],
      allergies: ['keine bekannt'],
      familyHistory: ['nicht relevant'],
      socialHistory: 'kürzlich von einer Reise aus Südostasien zurückgekehrt (vor 5 Tagen)',
      smoking: 'Nichtraucher',
      alcohol: 'gelegentlich',
      occupation: 'Ingenieur',
      patientConcerns: 'Sorge, sich mit etwas Ernstem angesteckt zu haben',
      emotionalState: 'erschöpft, besorgt',
      likelyDiagnosis: 'Fieber unklarer Genese, Reiseanamnese hochrelevant (z.B. Malaria-Ausschluss nötig)',
    },
    rubric: {
      requiredQuestions: [
        'Fieberverlauf und Höhe',
        'Begleitsymptome (Kopfschmerz, Husten, Durchfall, Hautausschlag)',
        'Reiseanamnese (essenziell!)',
        'Impfstatus, insbesondere Reiseimpfungen',
        'Kontakt zu Erkrankten',
        'Schüttelfrost',
      ],
      optionalQuestions: ['Insektenstiche während der Reise', 'Nahrungsmittel/Wasserkonsum im Ausland'],
      criticalOmissions: ['Nichterfragen der Reiseanamnese — kritischer Fehler bei Fieber nach Tropenaufenthalt'],
      patientLanguageTargets: ['"hohes Fieber mit Schüttelfrost" patientenverständlich beschreiben lassen'],
      terminologyTargets: ['Fieber unklarer Genese', 'Reiseanamnese', 'Inkubationszeit'],
      communicationTargets: ['Ansteckungssorgen sachlich und beruhigend, aber ehrlich ansprechen'],
      scoringWeights: { anamnesis: 35, communication: 15, patientLanguage: 10, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'husten-01',
    title: 'Anhaltender Husten',
    specialty: 'Pneumologie',
    difficulty: 1,
    estimatedMinutes: 12,
    patientName: 'Frau Kowalski',
    patientAge: 52,
    patientSex: 'weiblich',
    openingStatement: 'Ich huste jetzt schon seit drei Wochen, das will einfach nicht besser werden.',
    caseData: {
      chiefComplaint: 'Persistierender Husten seit drei Wochen',
      onset: 'Schleichend vor drei Wochen, nach einem grippalen Infekt',
      duration: '3 Wochen',
      characteristics: ['zunächst produktiv, jetzt eher trocken', 'verstärkt nachts'],
      positiveFindings: ['leichter Gewichtsverlust (2kg)', 'gelegentliches Nachtschwitzen'],
      negativeFindings: ['kein Blut im Auswurf', 'kein akutes Fieber', 'keine Brustschmerzen'],
      pastMedicalHistory: ['keine relevanten Vorerkrankungen'],
      medications: ['keine'],
      allergies: ['keine bekannt'],
      familyHistory: ['nicht relevant'],
      socialHistory: 'verheiratet, arbeitet in der Altenpflege',
      smoking: '15 py, aktuell rauchend',
      alcohol: 'selten',
      occupation: 'Altenpflegerin',
      patientConcerns: 'Sorge um eine ernsthafte Lungenerkrankung, evtl. Krebs',
      emotionalState: 'zunehmend besorgt',
      likelyDiagnosis: 'Abklärungsbedürftiger chronischer Husten — Differenzialdiagnose u.a. Tuberkulose bei B-Symptomatik und Berufsexposition',
    },
    rubric: {
      requiredQuestions: [
        'Dauer des Hustens (über 3 Wochen = chronisch)',
        'Produktiv oder trocken',
        'Blut im Auswurf (Hämoptyse)',
        'B-Symptomatik (Gewichtsverlust, Nachtschweiß, Fieber)',
        'Rauchgewohnheiten',
        'Berufliche Exposition/Kontaktpersonen',
      ],
      optionalQuestions: ['Allergien', 'Sodbrennen als Hustenursache'],
      criticalOmissions: ['Nichterfragen der B-Symptomatik bei chronischem Husten', 'Nichterfragen von Hämoptyse'],
      patientLanguageTargets: ['"Husten, der nicht weggeht" statt "chronischer, persistierender Husten" verwenden'],
      terminologyTargets: ['chronischer Husten', 'Hämoptyse', 'B-Symptomatik'],
      communicationTargets: ['Krebsangst nicht ignorieren, aber auch nicht vorschnell bestätigen oder verharmlosen'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'uebelkeit-erbrechen-01',
    title: 'Übelkeit und Erbrechen',
    specialty: 'Gastroenterologie',
    difficulty: 1,
    estimatedMinutes: 12,
    patientName: 'Herr Petrov',
    patientAge: 38,
    patientSex: 'männlich',
    openingStatement: 'Mir ist seit gestern Abend ständig übel, und ich musste mich schon mehrfach übergeben.',
    caseData: {
      chiefComplaint: 'Akute Übelkeit mit rezidivierendem Erbrechen',
      onset: 'Gestern Abend, ca. 2 Stunden nach dem Abendessen',
      duration: '18 Stunden',
      characteristics: ['nicht-blutiges Erbrechen', 'mehrfach (ca. 6-mal)', 'begleitet von krampfartigen Bauchschmerzen'],
      positiveFindings: ['wässriger Durchfall seit heute Morgen', 'leichtes Fieber (37,9°C)', 'reduzierte Flüssigkeitsaufnahme'],
      negativeFindings: ['kein Blut im Erbrochenen', 'kein Blut im Stuhl', 'keine Reisetätigkeit'],
      pastMedicalHistory: ['keine relevanten Vorerkrankungen'],
      medications: ['keine'],
      allergies: ['keine bekannt'],
      familyHistory: ['nicht relevant'],
      socialHistory: 'lebt mit Partnerin zusammen, die ähnliche Symptome hat',
      smoking: 'Nichtraucher',
      alcohol: 'gelegentlich',
      occupation: 'Koch',
      patientConcerns: 'Sorge um Austrocknung und Arbeitsausfall',
      emotionalState: 'erschöpft, unwohl',
      likelyDiagnosis: 'Akute virale Gastroenteritis',
    },
    rubric: {
      requiredQuestions: [
        'Häufigkeit und Charakter des Erbrechens',
        'Blut im Erbrochenen oder Stuhl',
        'Begleitender Durchfall',
        'Fieber',
        'Ähnliche Symptome bei Kontaktpersonen',
        'Flüssigkeitsaufnahme/Zeichen der Dehydratation',
        'Nahrungsmittelanamnese',
      ],
      optionalQuestions: ['Reiseanamnese', 'Medikamenteneinnahme vor Symptombeginn'],
      criticalOmissions: ['Nichterfragen von Dehydratationszeichen', 'Nichterfragen von Blut im Erbrochenen/Stuhl'],
      patientLanguageTargets: ['"Ich musste mich übergeben" statt "Emesis" im Patientengespräch aufgreifen'],
      terminologyTargets: ['Gastroenteritis', 'Emesis', 'Dehydratation'],
      communicationTargets: ['praktische Sorgen (Arbeitsausfall) ernst nehmen, klare Verhaltensempfehlungen geben'],
      scoringWeights: { anamnesis: 30, communication: 15, patientLanguage: 15, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
  {
    slug: 'beinschmerzen-01',
    title: 'Schwellung und Schmerzen im Bein',
    specialty: 'Angiologie',
    difficulty: 2,
    estimatedMinutes: 15,
    patientName: 'Frau Hoffmann',
    patientAge: 61,
    patientSex: 'weiblich',
    openingStatement: 'Mein rechtes Bein ist seit gestern geschwollen und tut weh.',
    caseData: {
      chiefComplaint: 'Einseitige Beinschwellung mit Schmerzen',
      onset: 'Gestern bemerkt, langsam zunehmend',
      duration: '24 Stunden',
      characteristics: ['Schwellung des rechten Unterschenkels', 'Schmerz bei Berührung und beim Gehen', 'Wärmegefühl'],
      positiveFindings: ['Rötung der Haut', 'Spannungsgefühl im Bein'],
      negativeFindings: ['keine offene Wunde', 'kein Fieber', 'keine Atemnot', 'kein Thoraxschmerz'],
      pastMedicalHistory: ['Langstreckenflug vor 4 Tagen (12 Stunden)', 'Adipositas'],
      medications: ['orale Kontrazeption'],
      allergies: ['keine bekannt'],
      familyHistory: ['Mutter hatte eine Thrombose'],
      socialHistory: 'verheiratet, arbeitet im Büro, überwiegend sitzend',
      smoking: 'aktuell rauchend, 10 py',
      alcohol: 'gelegentlich',
      occupation: 'Bürokauffrau',
      patientConcerns: 'Sorge, dass ein Gerinnsel in die Lunge wandern könnte',
      emotionalState: 'ängstlich, angespannt',
      likelyDiagnosis: 'Verdacht auf tiefe Beinvenenthrombose — hohes Risiko durch Flugreise, Rauchen und orale Kontrazeption',
    },
    rubric: {
      requiredQuestions: [
        'Einseitigkeit der Schwellung',
        'Schmerzcharakter und Auslöser',
        'Risikofaktoren (lange Immobilisation, Flugreise, Hormone, Rauchen)',
        'Familienanamnese für Thrombosen',
        'Begleitsymptome, insbesondere Atemnot/Thoraxschmerz (Lungenembolie!)',
        'Hautveränderungen (Rötung, Wärme)',
      ],
      optionalQuestions: ['frühere Thrombosen', 'Krampfadern'],
      criticalOmissions: [
        'Nichterfragen von Atemnot/Thoraxschmerz — kritisch zum Ausschluss einer Lungenembolie',
        'Nichterfragen der Risikofaktoren (Flugreise, Kontrazeption, Rauchen)',
      ],
      patientLanguageTargets: ['"geschwollenes, schmerzendes Bein" statt "Unterschenkelödem" im Gespräch verwenden'],
      terminologyTargets: ['tiefe Beinvenenthrombose', 'Lungenembolie', 'Immobilisation'],
      communicationTargets: ['Dringlichkeit vermitteln, ohne Panik auszulösen'],
      scoringWeights: { anamnesis: 35, communication: 15, patientLanguage: 10, medicalTerminology: 15, completeness: 15, languageAccuracy: 10 },
    },
  },
];
